version: '3'
services:
    netbox:
        build: .
        image: digitalocean/netbox:v2.0-beta2
        depends_on:
        - postgres
        - proxy
        env_file: netbox.env
        volumes:
        - netbox-nginx-config:/etc/netbox-nginx/
        - netbox-static-files:/opt/netbox/netbox/static
    proxy:
        image: nginx:1.11-alpine
        command: nginx -g 'daemon off;' -c /etc/netbox-nginx/nginx.conf
        ports:
        - 80
        volumes:
        - netbox-static-files:/opt/netbox/netbox/static
        - netbox-nginx-config:/etc/netbox-nginx/
    postgres:
        image: postgres:9.6-alpine
        environment:
            POSTGRES_USER: netbox
            POSTGRES_PASSWORD: J5brHrAXFLQSif0K
            POSTGRES_DB: netbox
    shepard:
        build: .
        image: "denzuko-forked/shepherd:latest"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    netbox-static-files:
        driver: local
    netbox-nginx-config:
        driver: local
